### ISSUE TITLE
Unable to login with Demon Hunter Character

### ISSUE THREAD

**Issue by Project-Root** [ottconnect/Legion#96]
Hello, yes as the title says for some reason im unable to login with my demon hunter character anymore, i get error message saying the following
*Login for that race, class, or character is currently disabled.*
Im not sure if ive done something wrong in the database or what i did wrong

**Comment by Project-Root** [comment]
Also it seems that i cant make burning crusade, mop, cataclysm, legion characters for some reason

**Comment by ottconnect** [comment]
you must of set your expansion in your account to something else, cannot reproduce the issue because the user modified his account expansion that prevents him from logging in at this time, also if you did a character table and auth table transfer that also might be an issue of missing tables.


Please re-create an account command

bnetaccount create user@apex.com password

then log in and see if you have the issue.

**Comment by Project-Root** [comment]
I managed to fix the issue by command *account set addon 2#1 6*
Creating new account does not replicates the issue
